package today.bonfire.oss.jutils.constants;

import lombok.Getter;
import lombok.experimental.Accessors;

@Getter
@Accessors(fluent = true)
public enum CountryCode {
  AD(ContinentCodes.EU, "Andorra", "Andorra la Vella", "ca", "^(?:AD)*(\\d{3})$"),
  AE(ContinentCodes.AS, "United Arab Emirates", "Abu Dhabi", "ar-AE", "^\\d{5}-\\d{5}$"),
  AF(ContinentCodes.AS, "Afghanistan", "Kabul", "fa-AF", ""),
  AG(ContinentCodes.NA, "Antigua and Barbuda", "St. John's", "en-AG", ""),
  AI(ContinentCodes.NA, "Anguilla", "The Valley", "en-AI", "^(?:AZ)*(\\d{4})$"),
  AL(ContinentCodes.EU, "Albania", "Tirana", "sq", "^(\\d{4})$"),
  AM(ContinentCodes.AS, "Armenia", "Yerevan", "hy", "^(\\d{6})$"),
  AO(ContinentCodes.AF, "Angola", "Luanda", "pt-AO", ""),
  AQ(ContinentCodes.AN, "Antarctica", "", "", ""),
  AR(ContinentCodes.SA, "Argentina", "Buenos Aires", "es-AR", "^[A-Z]?\\d{4}[A-Z]{0,3}$"),
  AS(ContinentCodes.OC, "American Samoa", "Pago Pago", "en-AS", "96799"),
  AT(ContinentCodes.EU, "Austria", "Vienna", "de-AT", "^(\\d{4})$"),
  AU(ContinentCodes.OC, "Australia", "Canberra", "en-AU", "^(\\d{4})$"),
  AW(ContinentCodes.NA, "Aruba", "Oranjestad", "nl-AW", ""),
  AX(ContinentCodes.EU, "Aland Islands", "Mariehamn", "sv-AX", "^(?:FI)*(\\d{5})$"),
  AZ(ContinentCodes.AS, "Azerbaijan", "Baku", "az", "^(?:AZ )*(\\d{4})$"),
  BA(ContinentCodes.EU, "Bosnia and Herzegovina", "Sarajevo", "bs", "^(\\d{5})$"),
  BB(ContinentCodes.NA, "Barbados", "Bridgetown", "en-BB", "^(?:BB)*(\\d{5})$"),
  BD(ContinentCodes.AS, "Bangladesh", "Dhaka", "bn-BD", "^(\\d{4})$"),
  BE(ContinentCodes.EU, "Belgium", "Brussels", "nl-BE", "^(\\d{4})$"),
  BF(ContinentCodes.AF, "Burkina Faso", "Ouagadougou", "fr-BF", ""),
  BG(ContinentCodes.EU, "Bulgaria", "Sofia", "bg", "^(\\d{4})$"),
  BH(ContinentCodes.AS, "Bahrain", "Manama", "ar-BH", "^(\\d{3}\\d?)$"),
  BI(ContinentCodes.AF, "Burundi", "Gitega", "fr-BI", ""),
  BJ(ContinentCodes.AF, "Benin", "Porto-Novo", "fr-BJ", ""),
  BL(ContinentCodes.NA, "Saint Barthelemy", "Gustavia", "fr", "^(\\d{5})$"),
  BM(ContinentCodes.NA, "Bermuda", "Hamilton", "en-BM", "^([A-Z]{2}\\d{2})$"),
  BN(ContinentCodes.AS, "Brunei", "Bandar Seri Begawan", "ms-BN", "^([A-Z]{2}\\d{4})$"),
  BO(ContinentCodes.SA, "Bolivia", "Sucre", "es-BO", ""),
  BQ(ContinentCodes.NA, "Bonaire, Saint Eustatius and Saba ", "", "nl", ""),
  BR(ContinentCodes.SA, "Brazil", "Brasilia", "pt-BR", "^\\d{5}-\\d{3}$"),
  BS(ContinentCodes.NA, "Bahamas", "Nassau", "en-BS", ""),
  BT(ContinentCodes.AS, "Bhutan", "Thimphu", "dz", ""),
  BV(ContinentCodes.AN, "Bouvet Island", "", "", ""),
  BW(ContinentCodes.AF, "Botswana", "Gaborone", "en-BW", ""),
  BY(ContinentCodes.EU, "Belarus", "Minsk", "be", "^(\\d{6})$"),
  BZ(ContinentCodes.NA, "Belize", "Belmopan", "en-BZ", ""),
  CA(ContinentCodes.NA, "Canada", "Ottawa", "en-CA", "^([ABCEGHJKLMNPRSTVXY]\\d[ABCEGHJKLMNPRSTVWXYZ]) ?(\\d[ABCEGHJKLMNPRSTVWXYZ]\\d)$ "),
  CC(ContinentCodes.AS, "Cocos Islands", "West Island", "ms-CC", "^(\\d{4})$"),
  CD(ContinentCodes.AF, "Democratic Republic of the Congo", "Kinshasa", "fr-CD", ""),
  CF(ContinentCodes.AF, "Central African Republic", "Bangui", "fr-CF", ""),
  CG(ContinentCodes.AF, "Republic of the Congo", "Brazzaville", "fr-CG", ""),
  CH(ContinentCodes.EU, "Switzerland", "Bern", "de-CH", "^(\\d{4})$"),
  CI(ContinentCodes.AF, "Ivory Coast", "Yamoussoukro", "fr-CI", ""),
  CK(ContinentCodes.OC, "Cook Islands", "Avarua", "en-CK", ""),
  CL(ContinentCodes.SA, "Chile", "Santiago", "es-CL", "^(\\d{7})$"),
  CM(ContinentCodes.AF, "Cameroon", "Yaounde", "en-CM", ""),
  CN(ContinentCodes.AS, "China", "Beijing", "zh-CN", "^(\\d{6})$"),
  CO(ContinentCodes.SA, "Colombia", "Bogota", "es-CO", "^(\\d{6})$"),
  CR(ContinentCodes.NA, "Costa Rica", "San Jose", "es-CR", "^(\\d{5})$"),
  CU(ContinentCodes.NA, "Cuba", "Havana", "es-CU", "^(?:CP)*(\\d{5})$"),
  CV(ContinentCodes.AF, "Cabo Verde", "Praia", "pt-CV", "^(\\d{4})$"),
  CW(ContinentCodes.NA, "Curacao", " Willemstad", "nl", ""),
  CX(ContinentCodes.OC, "Christmas Island", "Flying Fish Cove", "en", "^(\\d{4})$"),
  CY(ContinentCodes.EU, "Cyprus", "Nicosia", "el-CY", "^(\\d{4})$"),
  CZ(ContinentCodes.EU, "Czechia", "Prague", "cs", "^\\d{3}\\s?\\d{2}$"),
  DE(ContinentCodes.EU, "Germany", "Berlin", "de", "^(\\d{5})$"),
  DJ(ContinentCodes.AF, "Djibouti", "Djibouti", "fr-DJ", ""),
  DK(ContinentCodes.EU, "Denmark", "Copenhagen", "da-DK", "^(\\d{4})$"),
  DM(ContinentCodes.NA, "Dominica", "Roseau", "en-DM", ""),
  DO(ContinentCodes.NA, "Dominican Republic", "Santo Domingo", "es-DO", "^(\\d{5})$"),
  DZ(ContinentCodes.AF, "Algeria", "Algiers", "ar-DZ", "^(\\d{5})$"),
  EC(ContinentCodes.SA, "Ecuador", "Quito", "es-EC", "^([a-zA-Z]\\d{4}[a-zA-Z])$"),
  EE(ContinentCodes.EU, "Estonia", "Tallinn", "et", "^(\\d{5})$"),
  EG(ContinentCodes.AF, "Egypt", "Cairo", "ar-EG", "^(\\d{5})$"),
  EH(ContinentCodes.AF, "Western Sahara", "El-Aaiun", "ar", ""),
  ER(ContinentCodes.AF, "Eritrea", "Asmara", "aa-ER", ""),
  ES(ContinentCodes.EU, "Spain", "Madrid", "es-ES", "^(\\d{5})$"),
  ET(ContinentCodes.AF, "Ethiopia", "Addis Ababa", "am", "^(\\d{4})$"),
  FI(ContinentCodes.EU, "Finland", "Helsinki", "fi-FI", "^(?:FI)*(\\d{5})$"),
  FJ(ContinentCodes.OC, "Fiji", "Suva", "en-FJ", ""),
  FK(ContinentCodes.SA, "Falkland Islands", "Stanley", "en-FK", "FIQQ 1ZZ"),
  FM(ContinentCodes.OC, "Micronesia", "Palikir", "en-FM", "^(\\d{5})$"),
  FO(ContinentCodes.EU, "Faroe Islands", "Torshavn", "fo", "^(?:FO)*(\\d{3})$"),
  FR(ContinentCodes.EU, "France", "Paris", "fr-FR", "^(\\d{5})$"),
  GA(ContinentCodes.AF, "Gabon", "Libreville", "fr-GA", ""),
  GB(ContinentCodes.EU, "United Kingdom", "London", "en-GB",
     "^([Gg][Ii][Rr]\\s?0[Aa]{2})|((([A-Za-z][0-9]{1,2})|(([A-Za-z][A-Ha-hJ-Yj-y][0-9]{1,2})|(([A-Za-z][0-9][A-Za-z])|([A-Za-z][A-Ha-hJ-Yj-y][0-9]?[A-Za-z]))))\\s?[0-9][A-Za-z]{2})$"),
  GD(ContinentCodes.NA, "Grenada", "St. George's", "en-GD", ""),
  GE(ContinentCodes.AS, "Georgia", "Tbilisi", "ka", "^(\\d{4})$"),
  GF(ContinentCodes.SA, "French Guiana", "Cayenne", "fr-GF", "^((97|98)3\\d{2})$"),
  GG(ContinentCodes.EU, "Guernsey", "St Peter Port", "en", "^((?:(?:[A-PR-UWYZ][A-HK-Y]\\d[ABEHMNPRV-Y0-9]|[A-PR-UWYZ]\\d[A-HJKPS-UW0-9])\\s\\d[ABD-HJLNP-UW-Z]{2})|GIR\\s?0AA)$"),
  GH(ContinentCodes.AF, "Ghana", "Accra", "en-GH", ""),
  GI(ContinentCodes.EU, "Gibraltar", "Gibraltar", "en-GI", "GX11 1AA"),
  GL(ContinentCodes.NA, "Greenland", "Nuuk", "kl", "^(\\d{4})$"),
  GM(ContinentCodes.AF, "Gambia", "Banjul", "en-GM", ""),
  GN(ContinentCodes.AF, "Guinea", "Conakry", "fr-GN", ""),
  GP(ContinentCodes.NA, "Guadeloupe", "Basse-Terre", "fr-GP", "^((97|98)\\d{3})$"),
  GQ(ContinentCodes.AF, "Equatorial Guinea", "Malabo", "es-GQ", ""),
  GR(ContinentCodes.EU, "Greece", "Athens", "el-GR", "^(\\d{5})$"),
  GS(ContinentCodes.AN, "South Georgia and the South Sandwich Islands", "Grytviken", "en", "SIQQ 1ZZ"),
  GT(ContinentCodes.NA, "Guatemala", "Guatemala City", "es-GT", "^(\\d{5})$"),
  GU(ContinentCodes.OC, "Guam", "Hagatna", "en-GU", "^(969\\d{2})$"),
  GW(ContinentCodes.AF, "Guinea-Bissau", "Bissau", "pt-GW", "^(\\d{4})$"),
  GY(ContinentCodes.SA, "Guyana", "Georgetown", "en-GY", ""),
  HK(ContinentCodes.AS, "Hong Kong", "Hong Kong", "zh-HK", "^(\\d{6})$"),
  HM(ContinentCodes.AN, "Heard Island and McDonald Islands", "", "", "^(\\d{4})$"),
  HN(ContinentCodes.NA, "Honduras", "Tegucigalpa", "es-HN", "^(\\d{6})$"),
  HR(ContinentCodes.EU, "Croatia", "Zagreb", "hr-HR", "^(?:HR)*(\\d{5})$"),
  HT(ContinentCodes.NA, "Haiti", "Port-au-Prince", "ht", "^(?:HT)*(\\d{4})$"),
  HU(ContinentCodes.EU, "Hungary", "Budapest", "hu-HU", "^(\\d{4})$"),
  ID(ContinentCodes.AS, "Indonesia", "Jakarta", "id", "^(\\d{5})$"),
  IE(ContinentCodes.EU, "Ireland", "Dublin", "en-IE", "^(D6W|[AC-FHKNPRTV-Y][0-9]{2})\\s?([AC-FHKNPRTV-Y0-9]{4})"),
  IL(ContinentCodes.AS, "Israel", "Jerusalem", "he", "^(\\d{7}|\\d{5})$"),
  IM(ContinentCodes.EU, "Isle of Man", "Douglas", "en", "^((?:(?:[A-PR-UWYZ][A-HK-Y]\\d[ABEHMNPRV-Y0-9]|[A-PR-UWYZ]\\d[A-HJKPS-UW0-9])\\s\\d[ABD-HJLNP-UW-Z]{2})|GIR\\s?0AA)$"),
  IN(ContinentCodes.AS, "India", "New Delhi", "en-IN", "^(\\d{6})$"),
  IO(ContinentCodes.AS, "British Indian Ocean Territory", "Diego Garcia", "en-IO", "BBND 1ZZ"),
  IQ(ContinentCodes.AS, "Iraq", "Baghdad", "ar-IQ", "^(\\d{5})$"),
  IR(ContinentCodes.AS, "Iran", "Tehran", "fa-IR", "^(\\d{10})$"),
  IS(ContinentCodes.EU, "Iceland", "Reykjavik", "is", "^(\\d{3})$"),
  IT(ContinentCodes.EU, "Italy", "Rome", "it-IT", "^(\\d{5})$"),
  JE(ContinentCodes.EU, "Jersey", "Saint Helier", "en", "^((?:(?:[A-PR-UWYZ][A-HK-Y]\\d[ABEHMNPRV-Y0-9]|[A-PR-UWYZ]\\d[A-HJKPS-UW0-9])\\s\\d[ABD-HJLNP-UW-Z]{2})|GIR\\s?0AA)$"),
  JM(ContinentCodes.NA, "Jamaica", "Kingston", "en-JM", ""),
  JO(ContinentCodes.AS, "Jordan", "Amman", "ar-JO", "^(\\d{5})$"),
  JP(ContinentCodes.AS, "Japan", "Tokyo", "ja", "^\\d{3}-\\d{4}$"),
  KE(ContinentCodes.AF, "Kenya", "Nairobi", "en-KE", "^(\\d{5})$"),
  KG(ContinentCodes.AS, "Kyrgyzstan", "Bishkek", "ky", "^(\\d{6})$"),
  KH(ContinentCodes.AS, "Cambodia", "Phnom Penh", "km", "^(\\d{5})$"),
  KI(ContinentCodes.OC, "Kiribati", "Tarawa", "en-KI", ""),
  KM(ContinentCodes.AF, "Comoros", "Moroni", "ar", ""),
  KN(ContinentCodes.NA, "Saint Kitts and Nevis", "Basseterre", "en-KN", ""),
  KP(ContinentCodes.AS, "North Korea", "Pyongyang", "ko-KP", "^(\\d{6})$"),
  KR(ContinentCodes.AS, "South Korea", "Seoul", "ko-KR", "^(\\d{5})$"),
  XK(ContinentCodes.EU, "Kosovo", "Pristina", "sq", ""),
  KW(ContinentCodes.AS, "Kuwait", "Kuwait City", "ar-KW", "^(\\d{5})$"),
  KY(ContinentCodes.NA, "Cayman Islands", "George Town", "en-KY", ""),
  KZ(ContinentCodes.AS, "Kazakhstan", "Nur-Sultan", "kk", "^(\\d{6})$"),
  LA(ContinentCodes.AS, "Laos", "Vientiane", "lo", "^(\\d{5})$"),
  LB(ContinentCodes.AS, "Lebanon", "Beirut", "ar-LB", "^(\\d{4}(\\d{4})?)$"),
  LC(ContinentCodes.NA, "Saint Lucia", "Castries", "en-LC", ""),
  LI(ContinentCodes.EU, "Liechtenstein", "Vaduz", "de-LI", "^(\\d{4})$"),
  LK(ContinentCodes.AS, "Sri Lanka", "Colombo", "si", "^(\\d{5})$"),
  LR(ContinentCodes.AF, "Liberia", "Monrovia", "en-LR", "^(\\d{4})$"),
  LS(ContinentCodes.AF, "Lesotho", "Maseru", "en-LS", "^(\\d{3})$"),
  LT(ContinentCodes.EU, "Lithuania", "Vilnius", "lt", "^(?:LT)*(\\d{5})$"),
  LU(ContinentCodes.EU, "Luxembourg", "Luxembourg", "lb", "^(?:L-)?\\d{4}$"),
  LV(ContinentCodes.EU, "Latvia", "Riga", "lv", "^(?:LV)*(\\d{4})$"),
  LY(ContinentCodes.AF, "Libya", "Tripoli", "ar-LY", ""),
  MA(ContinentCodes.AF, "Morocco", "Rabat", "ar-MA", "^(\\d{5})$"),
  MC(ContinentCodes.EU, "Monaco", "Monaco", "fr-MC", "^(\\d{5})$"),
  MD(ContinentCodes.EU, "Moldova", "Chisinau", "ro", "^MD-\\d{4}$"),
  ME(ContinentCodes.EU, "Montenegro", "Podgorica", "sr", "^(\\d{5})$"),
  MF(ContinentCodes.NA, "Saint Martin", "Marigot", "fr", "^(\\d{5})$"),
  MG(ContinentCodes.AF, "Madagascar", "Antananarivo", "fr-MG", "^(\\d{3})$"),
  MH(ContinentCodes.OC, "Marshall Islands", "Majuro", "mh", "^969\\d{2}(-\\d{4})$"),
  MK(ContinentCodes.EU, "North Macedonia", "Skopje", "mk", "^(\\d{4})$"),
  ML(ContinentCodes.AF, "Mali", "Bamako", "fr-ML", ""),
  MM(ContinentCodes.AS, "Myanmar", "Nay Pyi Taw", "my", "^(\\d{5})$"),
  MN(ContinentCodes.AS, "Mongolia", "Ulaanbaatar", "mn", "^(\\d{6})$"),
  MO(ContinentCodes.AS, "Macao", "Macao", "zh", "^(\\d{6})$"),
  MP(ContinentCodes.OC, "Northern Mariana Islands", "Saipan", "fil", "^9695\\d{1}$"),
  MQ(ContinentCodes.NA, "Martinique", "Fort-de-France", "fr-MQ", "^(\\d{5})$"),
  MR(ContinentCodes.AF, "Mauritania", "Nouakchott", "ar-MR", ""),
  MS(ContinentCodes.NA, "Montserrat", "Plymouth", "en-MS", ""),
  MT(ContinentCodes.EU, "Malta", "Valletta", "mt", "^[A-Z]{3}\\s?\\d{4}$"),
  MU(ContinentCodes.AF, "Mauritius", "Port Louis", "en-MU", ""),
  MV(ContinentCodes.AS, "Maldives", "Male", "dv", "^(\\d{5})$"),
  MW(ContinentCodes.AF, "Malawi", "Lilongwe", "ny", "^(\\d{6})$"),
  MX(ContinentCodes.NA, "Mexico", "Mexico City", "es-MX", "^(\\d{5})$"),
  MY(ContinentCodes.AS, "Malaysia", "Kuala Lumpur", "ms-MY", "^(\\d{5})$"),
  MZ(ContinentCodes.AF, "Mozambique", "Maputo", "pt-MZ", "^(\\d{4})$"),
  NA(ContinentCodes.AF, "Namibia", "Windhoek", "en-NA", ""),
  NC(ContinentCodes.OC, "New Caledonia", "Noumea", "fr-NC", "^(\\d{5})$"),
  NE(ContinentCodes.AF, "Niger", "Niamey", "fr-NE", "^(\\d{4})$"),
  NF(ContinentCodes.OC, "Norfolk Island", "Kingston", "en-NF", "^(\\d{4})$"),
  NG(ContinentCodes.AF, "Nigeria", "Abuja", "en-NG", "^(\\d{6})$"),
  NI(ContinentCodes.NA, "Nicaragua", "Managua", "es-NI", "^(\\d{7})$"),
  NL(ContinentCodes.EU, "The Netherlands", "Amsterdam", "nl-NL", "^(\\d{4}\\s?[a-zA-Z]{2})$"),
  NO(ContinentCodes.EU, "Norway", "Oslo", "no", "^(\\d{4})$"),
  NP(ContinentCodes.AS, "Nepal", "Kathmandu", "ne", "^(\\d{5})$"),
  NR(ContinentCodes.OC, "Nauru", "Yaren", "na", "NRU68"),
  NU(ContinentCodes.OC, "Niue", "Alofi", "niu", "^(\\d{4})$"),
  NZ(ContinentCodes.OC, "New Zealand", "Wellington", "en-NZ", "^(\\d{4})$"),
  OM(ContinentCodes.AS, "Oman", "Muscat", "ar-OM", "^(\\d{3})$"),
  PA(ContinentCodes.NA, "Panama", "Panama City", "es-PA", "^(\\d{5})$"),
  PE(ContinentCodes.SA, "Peru", "Lima", "es-PE", "^(\\d{5})$"),
  PF(ContinentCodes.OC, "French Polynesia", "Papeete", "fr-PF", "^((97|98)7\\d{2})$"),
  PG(ContinentCodes.OC, "Papua New Guinea", "Port Moresby", "en-PG", "^(\\d{3})$"),
  PH(ContinentCodes.AS, "Philippines", "Manila", "tl", "^(\\d{4})$"),
  PK(ContinentCodes.AS, "Pakistan", "Islamabad", "ur-PK", "^(\\d{5})$"),
  PL(ContinentCodes.EU, "Poland", "Warsaw", "pl", "^\\d{2}-\\d{3}$"),
  PM(ContinentCodes.NA, "Saint Pierre and Miquelon", "Saint-Pierre", "fr-PM", "^(97500)$"),
  PN(ContinentCodes.OC, "Pitcairn", "Adamstown", "en-PN", "PCRN 1ZZ"),
  PR(ContinentCodes.NA, "Puerto Rico", "San Juan", "en-PR", "^00[679]\\d{2}(?:-\\d{4})?$"),
  PS(ContinentCodes.AS, "Palestinian Territory", "East Jerusalem", "ar-PS", ""),
  PT(ContinentCodes.EU, "Portugal", "Lisbon", "pt-PT", "^\\d{4}-\\d{3}\\s?[a-zA-Z]{0,25}$"),
  PW(ContinentCodes.OC, "Palau", "Melekeok", "pau", "^(96940)$"),
  PY(ContinentCodes.SA, "Paraguay", "Asuncion", "es-PY", "^(\\d{4})$"),
  QA(ContinentCodes.AS, "Qatar", "Doha", "ar-QA", ""),
  RE(ContinentCodes.AF, "Reunion", "Saint-Denis", "fr-RE", "^((97|98)(4|7|8)\\d{2})$"),
  RO(ContinentCodes.EU, "Romania", "Bucharest", "ro", "^(\\d{6})$"),
  RS(ContinentCodes.EU, "Serbia", "Belgrade", "sr", "^(\\d{5})$"),
  RU(ContinentCodes.EU, "Russia", "Moscow", "ru", "^(\\d{6})$"),
  RW(ContinentCodes.AF, "Rwanda", "Kigali", "rw", ""),
  SA(ContinentCodes.AS, "Saudi Arabia", "Riyadh", "ar-SA", "^(\\d{5})$"),
  SB(ContinentCodes.OC, "Solomon Islands", "Honiara", "en-SB", ""),
  SC(ContinentCodes.AF, "Seychelles", "Victoria", "en-SC", ""),
  SD(ContinentCodes.AF, "Sudan", "Khartoum", "ar-SD", "^(\\d{5})$"),
  SS(ContinentCodes.AF, "South Sudan", "Juba", "en", ""),
  SE(ContinentCodes.EU, "Sweden", "Stockholm", "sv-SE", "^(?:SE)?\\d{3}\\s\\d{2}$"),
  SG(ContinentCodes.AS, "Singapore", "Singapore", "cmn", "^(\\d{6})$"),
  SH(ContinentCodes.AF, "Saint Helena", "Jamestown", "en-SH", "^(STHL1ZZ)$"),
  SI(ContinentCodes.EU, "Slovenia", "Ljubljana", "sl", "^(?:SI)*(\\d{4})$"),
  SJ(ContinentCodes.EU, "Svalbard and Jan Mayen", "Longyearbyen", "no", "^(\\d{4})$"),
  SK(ContinentCodes.EU, "Slovakia", "Bratislava", "sk", "^\\d{3}\\s?\\d{2}$"),
  SL(ContinentCodes.AF, "Sierra Leone", "Freetown", "en-SL", ""),
  SM(ContinentCodes.EU, "San Marino", "San Marino", "it-SM", "^(4789\\d)$"),
  SN(ContinentCodes.AF, "Senegal", "Dakar", "fr-SN", "^(\\d{5})$"),
  SO(ContinentCodes.AF, "Somalia", "Mogadishu", "so-SO", "^([A-Z]{2}\\d{5})$"),
  SR(ContinentCodes.SA, "Suriname", "Paramaribo", "nl-SR", ""),
  ST(ContinentCodes.AF, "Sao Tome and Principe", "Sao Tome", "pt-ST", ""),
  SV(ContinentCodes.NA, "El Salvador", "San Salvador", "es-SV", "^(?:CP)*(\\d{4})$"),
  SX(ContinentCodes.NA, "Sint Maarten", "Philipsburg", "nl", ""),
  SY(ContinentCodes.AS, "Syria", "Damascus", "ar-SY", ""),
  SZ(ContinentCodes.AF, "Eswatini", "Mbabane", "en-SZ", "^([A-Z]\\d{3})$"),
  TC(ContinentCodes.NA, "Turks and Caicos Islands", "Cockburn Town", "en-TC", "^(TKCA 1ZZ)$"),
  TD(ContinentCodes.AF, "Chad", "N'Djamena", "fr-TD", "^(TKCA 1ZZ)$"),
  TF(ContinentCodes.AN, "French Southern Territories", "Port-aux-Francais", "fr", ""),
  TG(ContinentCodes.AF, "Togo", "Lome", "fr-TG", ""),
  TH(ContinentCodes.AS, "Thailand", "Bangkok", "th", "^(\\d{5})$"),
  TJ(ContinentCodes.AS, "Tajikistan", "Dushanbe", "tg", "^(\\d{6})$"),
  TK(ContinentCodes.OC, "Tokelau", "", "tkl", ""),
  TL(ContinentCodes.OC, "Timor Leste", "Dili", "tet", ""),
  TM(ContinentCodes.AS, "Turkmenistan", "Ashgabat", "tk", "^(\\d{6})$"),
  TN(ContinentCodes.AF, "Tunisia", "Tunis", "ar-TN", "^(\\d{4})$"),
  TO(ContinentCodes.OC, "Tonga", "Nuku'alofa", "to", ""),
  TR(ContinentCodes.AS, "Turkey", "Ankara", "tr-TR", "^(\\d{5})$"),
  TT(ContinentCodes.NA, "Trinidad and Tobago", "Port of Spain", "en-TT", ""),
  TV(ContinentCodes.OC, "Tuvalu", "Funafuti", "tvl", ""),
  TW(ContinentCodes.AS, "Taiwan", "Taipei", "zh-TW", "^(\\d{5})$"),
  TZ(ContinentCodes.AF, "Tanzania", "Dodoma", "sw-TZ", ""),
  UA(ContinentCodes.EU, "Ukraine", "Kyiv", "uk", "^(\\d{5})$"),
  UG(ContinentCodes.AF, "Uganda", "Kampala", "en-UG", ""),
  UM(ContinentCodes.OC, "United States Minor Outlying Islands", "", "en-UM", ""),
  US(ContinentCodes.NA, "United States", "Washington", "en-US", "^\\d{5}(-\\d{4})?$"),
  UY(ContinentCodes.SA, "Uruguay", "Montevideo", "es-UY", "^(\\d{5})$"),
  UZ(ContinentCodes.AS, "Uzbekistan", "Tashkent", "uz", "^(\\d{6})$"),
  VA(ContinentCodes.EU, "Vatican", "Vatican City", "la", "^(\\d{5})$"),
  VC(ContinentCodes.NA, "Saint Vincent and the Grenadines", "Kingstown", "en-VC", ""),
  VE(ContinentCodes.SA, "Venezuela", "Caracas", "es-VE", "^(\\d{4})$"),
  VG(ContinentCodes.NA, "British Virgin Islands", "Road Town", "en-VG", ""),
  VI(ContinentCodes.NA, "U.S. Virgin Islands", "Charlotte Amalie", "en-VI", "^008\\d{2}(?:-\\d{4})?$"),
  VN(ContinentCodes.AS, "Vietnam", "Hanoi", "vi", "^(\\d{6})$"),
  VU(ContinentCodes.OC, "Vanuatu", "Port Vila", "bi", ""),
  WF(ContinentCodes.OC, "Wallis and Futuna", "Mata Utu", "wls", "^(986\\d{2})$"),
  WS(ContinentCodes.OC, "Samoa", "Apia", "sm", "AS 96799"),
  YE(ContinentCodes.AS, "Yemen", "Sanaa", "ar-YE", ""),
  YT(ContinentCodes.AF, "Mayotte", "Mamoudzou", "fr-YT", "^(\\d{5})$"),
  ZA(ContinentCodes.AF, "South Africa", "Pretoria", "zu", "^(\\d{4})$"),
  ZM(ContinentCodes.AF, "Zambia", "Lusaka", "en-ZM", "^(\\d{5})$"),
  ZW(ContinentCodes.AF, "Zimbabwe", "Harare", "en-ZW", ""),
  CS(ContinentCodes.EU, "Serbia and Montenegro", "Belgrade", "cu", "^(\\d{5})$"),
  AN(ContinentCodes.NA, "Netherlands Antilles", "Willemstad", "nl-AN", ""),
  XX(ContinentCodes.XX, "Unknown", "", "", "");

  private final ContinentCodes continentCode;
  private final String         asciiName;
  private final String         capital;
  private final String         primaryLanguage;
  private final String         postCodeRegex;

  CountryCode(ContinentCodes continentCode, String name, String capital, String primaryLanguage, String postCodeRegex) {
    this.continentCode   = continentCode;
    this.asciiName       = name;
    this.capital         = capital;
    this.primaryLanguage = primaryLanguage;
    this.postCodeRegex   = postCodeRegex;
  }
}
